apiVersion: v1
data:
  nginx.conf: |
    http {
      server {
        location /overwrite {
          # Set Content-Type
          proxy_set_header Content-Type application/json;
          proxy_pass http://backend-server/overwrite;
        }

        location / {
          proxy_pass http://backend-server;
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
