apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-server
  name: backend-cluster
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-server
  type: ClusterIP
